#监控关闭
security:
  basic:
    enabled: false
management:
  security:
    enabled: false

spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/sport_app?useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5 # 初始化时建立物理连接的个数
      max-active: 30  # 最大连接池数量
      min-idle: 5 # 最小连接池数量
      max-wait: 60000 # 获取连接时最大等待时间，单位毫秒
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 # 连接保持空闲而不被驱逐的最小时间
      validation-query: SELECT 1 FROM DUAL # 用来检测连接是否有效的sql，要求是一个查询语句
      test-while-idle: true # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-on-borrow: false # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      pool-prepared-statements: true # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      max-pool-prepared-statement-per-connection-size: 50 # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      filters: stat,wall # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500 # 通过connectProperties属性来打开mergeSql功能；慢SQL记
      use-global-data-source-stat: true # 合并多个DruidDataSource的监控数据
      stat-view-servlet: # druid连接池监控
        login-username: admin
        login-password: admin
#  devtools: #开启热部署
#    restart:
#      enabled: false

  redis:
    host: 120.24.6.203
    port: 6379
    password: 123456

  rabbitmq:
    host:
    port:
    username:
    password:

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapper/*Mapper
  type-aliases-package: com.example.sportApp.model